name: eda3
channels:
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'ipython-sql=0.3.6=py36_1'
- !!python/unicode
  'ipywidgets=6.0.0=py36_0'
- !!python/unicode
  'jupyter_contrib_core=0.3.1=py36_0'
- !!python/unicode
  'jupyter_contrib_nbextensions=0.2.7=py36_0'
- !!python/unicode
  'jupyter_highlight_selected_word=0.0.11=py36_0'
- !!python/unicode
  'jupyter_latex_envs=1.3.8.2=py36_1'
- !!python/unicode
  'jupyter_nbextensions_configurator=0.2.4=py36_0'
- !!python/unicode
  'mpld3=0.3=py36_0'
- !!python/unicode
  'prettytable=0.7.2=py36_0'
- !!python/unicode
  'anaconda-client=1.6.3=py36_0'
- !!python/unicode
  'appnope=0.1.0=py36_0'
- !!python/unicode
  'bleach=1.5.0=py36_0'
- !!python/unicode
  'clyent=1.2.2=py36_0'
- !!python/unicode
  'cycler=0.10.0=py36_0'
- !!python/unicode
  'decorator=4.0.11=py36_0'
- !!python/unicode
  'entrypoints=0.2.2=py36_1'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'html5lib=0.999=py36_0'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'ipykernel=4.6.1=py36_0'
- !!python/unicode
  'ipython=6.0.0=py36_0'
- !!python/unicode
  'ipython_genutils=0.2.0=py36_0'
- !!python/unicode
  'jinja2=2.9.6=py36_0'
- !!python/unicode
  'jsonschema=2.6.0=py36_0'
- !!python/unicode
  'jupyter_client=5.0.1=py36_0'
- !!python/unicode
  'jupyter_console=5.1.0=py36_0'
- !!python/unicode
  'jupyter_core=4.3.0=py36_0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'markupsafe=0.23=py36_2'
- !!python/unicode
  'matplotlib=2.0.0=np112py36_0'
- !!python/unicode
  'mistune=0.7.4=py36_0'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'nbconvert=5.1.1=py36_0'
- !!python/unicode
  'nbformat=4.3.0=py36_0'
- !!python/unicode
  'notebook=5.0.0=py36_0'
- !!python/unicode
  'numpy=1.12.1=py36_0'
- !!python/unicode
  'openssl=1.0.2k=1'
- !!python/unicode
  'pandas=0.19.2=np112py36_1'
- !!python/unicode
  'pandocfilters=1.4.1=py36_0'
- !!python/unicode
  'path.py=10.3.1=py36_0'
- !!python/unicode
  'patsy=0.4.1=py36_0'
- !!python/unicode
  'pexpect=4.2.1=py36_0'
- !!python/unicode
  'pickleshare=0.7.4=py36_0'
- !!python/unicode
  'pip=9.0.1=py36_1'
- !!python/unicode
  'pivottablejs=2.7.0=py36_0'
- !!python/unicode
  'prompt_toolkit=1.0.14=py36_0'
- !!python/unicode
  'psutil=5.2.2=py36_0'
- !!python/unicode
  'ptyprocess=0.5.1=py36_0'
- !!python/unicode
  'pygments=2.2.0=py36_0'
- !!python/unicode
  'pyparsing=2.1.4=py36_0'
- !!python/unicode
  'pyqt=5.6.0=py36_2'
- !!python/unicode
  'python=3.6.1=0'
- !!python/unicode
  'python-dateutil=2.6.0=py36_0'
- !!python/unicode
  'pytz=2017.2=py36_0'
- !!python/unicode
  'pyyaml=3.12=py36_0'
- !!python/unicode
  'pyzmq=16.0.2=py36_0'
- !!python/unicode
  'qgrid=0.3.2=py36_0'
- !!python/unicode
  'qt=5.6.2=0'
- !!python/unicode
  'qtconsole=4.3.0=py36_0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'requests=2.13.0=py36_0'
- !!python/unicode
  'scikit-learn=0.18.1=np112py36_1'
- !!python/unicode
  'scipy=0.19.0=np112py36_0'
- !!python/unicode
  'seaborn=0.7.1=py36_0'
- !!python/unicode
  'setuptools=27.2.0=py36_0'
- !!python/unicode
  'simplegeneric=0.8.1=py36_1'
- !!python/unicode
  'sip=4.18=py36_0'
- !!python/unicode
  'six=1.10.0=py36_0'
- !!python/unicode
  'sqlalchemy=1.1.9=py36_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'sqlparse=0.1.19=py36_0'
- !!python/unicode
  'statsmodels=0.8.0=np112py36_0'
- !!python/unicode
  'terminado=0.6=py36_0'
- !!python/unicode
  'testpath=0.3=py36_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'tornado=4.5.1=py36_0'
- !!python/unicode
  'tqdm=4.11.2=py36_0'
- !!python/unicode
  'traitlets=4.3.2=py36_0'
- !!python/unicode
  'wcwidth=0.1.7=py36_0'
- !!python/unicode
  'wheel=0.29.0=py36_0'
- !!python/unicode
  'widgetsnbextension=2.0.0=py36_0'
- !!python/unicode
  'xz=5.2.2=1'
- !!python/unicode
  'yaml=0.1.6=0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - branca==0.2.0
  - colorama==0.3.9
  - folium==0.3.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-contrib-core==0.3.1
  - jupyter-contrib-nbextensions==0.2.7
  - jupyter-core==4.3.0
  - jupyter-highlight-selected-word==0.0.11
  - jupyter-latex-envs==1.3.8.2
  - jupyter-nbextensions-configurator==0.2.4
  - missingno==0.3.5
  - nbdime==0.2.0
  - pandas-profiling==1.4.0
  - prompt-toolkit==1.0.14

